name: Docker Image CI [master, develop]

on:
  push:
    branches: 
      - master
      - develop
      - docker-master-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set Repo Branch Name
      run: export branch_name=$(echo $GITHUB_REF | sed -e "s/^refs\/heads\///")
      shell: bash
      
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --tag jolian88/gateone:$branch_name
      shell: bash
      
    - name: Log in to DockerHub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      shell: bash
    
    - name: Publish image to DockerHub
      run: docker push jolian88/gateone:$branch_name
      shell: bash
