name: Docker Image CI [master, develop]

on:
  push:
    branches: 
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set Repo Branch Name
      run: branch_name=$(echo $GITHUB_REF | sed -e "s/^refs\/heads\///")
      
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --tag jolian88/gateone:$branch_name
      
