name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure environment variables
      run: BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s/^refs\/tags\/v//")
          
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jolian88/gateone:$BRANCH_NAME
      
